# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: FreightForward Documentation
email: contact@resgef.com
description: >- # this means to ignore newlines until "baseurl:"
  FreightForward is a freight documents generator software, with integrated job costing and accounting. The software is FOSS and licensed under GPL-2.0
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: MinhajulAnwar
github_username: minhajme

# Build settings
theme: just-the-docs
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

#https://pmarsceill.github.io/just-the-docs/docs/configuration/
search_enabled: false
aux_links:
  "FreightForward": https://github.com/minhajme/freightforward
  "Developer(Minhajul Anwar)": https://github.com/minhajme
  "Resgef Labs": https://resgef.com
aux_links_new_tab: true

ga_tracking: UA-202058120-1
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true by default)

#collections:
#  install:
#    permalink: "/:collection/:path/"
#    output: true
#  tutorials:
#    permalink: "/:collection/:path/"
#    output: true
#
#just_the_docs:
#  collections:
#    install:
#      name: Install Notes
#    tutorials:
#      name: Tutorials
